# Site settings
title: Joanne Zhou
description: Welcome to my website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://jwnzhou.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joanne Zhou
user_description: I'm a dietitian in Toronto, that dabbles in tech.
user_title: Techy Dietitian
# twitter_username: jwnzhou
# github_username:  jwnzhou

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
